backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow


collections:

#config collection
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"
          - label: "LinkedIn account"
            name: "linkedin_account"
            widget: "string"
          - label: "Email direction"
            name: "email_direction"
            widget: "string"

  #meta collection
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "projects"
    label: "Projects"
    folder: "content/projects/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: "public/images/green_placeholder.jpg"
      - label: "Start Date"
        name: "start_date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "End Date"
        name: "end_date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Repository"
        name: "repository"
        widget: "string"
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Technologies
        label_singular: "Technology"
        name: "technologies"
        widget: list
        summary: "{{fields.technology}}"
        field:
          label: Technology
          name: technology
          widget: String
      - label: "Related Posts"
        label_singular: "Related Post"
        name: "related_posts"
        widget: list
        summary: "{{fields.related_posts}}"
        field:
          label: "Related post"
          name: related_post
          widget: relation
          collection: "posts"
          search_fields: [ "{{title}}" ]
          value_field: "{{slug}}"
          display_fields: [ "{{title}}" ]
      - label: "Body"
        name: "body"
        widget: "markdown"
  #posts collection
  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: "public/images/green_placeholder.jpg"
      - label: "Summary"
        name: "summary"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  #front page collection
  - name: "frontpage"
    label: "Front page"
    delete: false
    editor:
      preview: false
    files:
      - name: "frontPage"
        label: "Front Page"
        file: "frontPage.json"
        description: "Information shown in the front page"
        fields:
          - label: Information Cards
            name: information_cards
            widget: list
            fields:
              - label: "Card Slug"
                name: "card_slug"
                widget: "string"
              - label: "Card Title"
                name: "card_title"
                widget: "string"
              - label: "Card Subtitle"
                name: "card_subtitle"
                widget: "string"
              - label: "Card Summary"
                name: "card_summary"
                widget: "string"
              - label: "Featured Image"
                name: "card_image"
                widget: "image"